plugins:
  - C:\Users\bhaum\.console-ninja\.yarn\plugin.js
compressionLevel: 9
enableColors: true
enableTimers: true
enableGlobalCache: true
enableProgressBars: true
globalFolder: C:\Users\bhaum\.yarn
progressBarStyle: jack
tsEnableAutoTypes: true
nodeLinker: node-modules
pnpMode: loose
pnpUnpluggedFolder: C:\Users\bhaum\.yarn\unplugged
